version: "3.9"
services:
  honeybadgerContainer:
    container_name: honeybadgerContainer
    image: node:17-buster
    depends_on:
      - backend
    volumes:
      - ./:/home/node/app
      - honeybadgerVolume:/home/node/app/node_modules
    working_dir: /home/node
    command: sh -c "cd ./app && npm install && npm run build"

volumes:
  honeybadgerVolume:
    driver: local